import Header from "@/components/Header";
import Provider from "@/components/Provider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icon: "/icon.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header />
          {/* <div>navbar</div> */}
          {/* <div>search</div> */}
          {children}
        </Provider>
      </body>
    </html>
  );
}
